### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by SwixDevs** [zajrik/yamdbf-addon-dm-manager#1]
I have done everything written there correctly, tried everything, but it doesn't work.

**Comment by zajrik** [comment]
Given that YAMDBF is so horribly out of date I'm not surprised. If I ever get around to updating YAMDBF I'll test this out and see what needs to be done to get it up and running again.

**Comment by zajrik** [comment]
I've updated YAMDBF indev to work with the latest Discord.js release, and I've now pushed an indev update for this plugin to work with the latest YAMDBF indev and the latest Discord.js release. In the process, I changed how indev versions of this plugin are released and installed. You can now install them from NPM with either of the following (depending on which package manager you prefer):
- `npm install --save @yamdbf/dm-manager@indev`
- `yarn add @yamdbf/dm-manager@indev`

(YAMDBF indev is also published to NPM now instead of GitHub, so you'll wanna install the new version from there as well)

I'm going to go ahead and close this issue as I can't imagine you're going to continue having problems with this if you're using it as detailed in the README.
